# Generated by Django 5.0.3 on 2024-03-19 16:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generates_code, max_length=8, unique=True),
        ),
    ]
